import { Grid, Repeater, ComponentCollection } from '@genny-project/layson';
import { 
  BucketView,
  Sidebar,
  ImageView,
  TreeView,
  IconSmall,
  GennyTreeView,
  GennyImageView,
  GennyBucketView,
  GennyNotification,
  GennyHeader,
  Header,
  Footer,
  Card,
  AppHolder,
  GennyForm,
  GennyTable,
  GennyList,
  GennyButton,
  AppContent,
  Button,
  Dropdown,
  Status,
} from 'views/components';

export default new ComponentCollection({
  Grid,
  Repeater,
  BucketView,
  Sidebar,
  ImageView,
  TreeView,
  Card,
  GennyTreeView,
  GennyImageView,
  GennyHeader,
  Header,
  Footer,
  AppHolder,
  GennyForm,
  GennyNotification,
  GennyTable,
  GennyBucketView,
  IconSmall,
  GennyList,
  GennyButton,
  AppContent,
  Button,
  Dropdown,
  Status,
});
