export const APP_START = 'APP_START';

/* Auth */
export const AUTH_LOGGED_IN = 'AUTH_LOGGED_IN';
export const AUTH_LOGGED_OUT = 'AUTH_LOGGED_OUT';

/* Keycloak */
export const RECEIVE_KEYCLOAK_CONFIG = 'RECEIVE_KEYCLOAK_CONFIG';
export const ERROR_RECEIVE_KEYCLOAK_CONFIG = 'ERROR_RECEIVE_KEYCLOAK_CONFIG';
